import 'dart:ffi';
import 'dart:typed_data';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import '../widgets/custom_snackbar.dart';

class AddPet {
  static var auth = FirebaseFirestore.instance;
  static Future<void> AddPetDetails({
    required String id,
    required String petname,
    required String breed,
    required String color,
    required String dob,
    required String weight,
    required String lastHeat,
    required String nextHeat,
    required String gender,
    required String spayedNeutered,
    required String vetName,
    required String mobile,
    required String petProneTo,
    required String petPossessive,
    required String parkDaycare,
    required String petAround,
    required String petDescribe,
    required String petExercise,
    required String mrngtime,
    required String afrntime,
    required String evetime,
    required String nyttime,
    required String mrngdiet,
    required String afrndiet,
    required String evediet,
    required String nytdiet,
    required String mrngqyt,
    required String afrnqyt,
    required String eveqyt,
    required String nytqyt,
    required String place,
    required String date,
    //
    required String isMedicaion,
    required String medication1,
    required String dosage1,
    required String prescribe1,
    required String medication2,
    required String dosage2,
    required String prescribe2,
    required String medication3,
    required String dosage3,
    required String prescribe3,
    required String isVaccinationC,
    required String rabieslast,
    required String rabiesnext,
    required String sevenlast,
    required String sevennext,
    required String bordetalast,
    required String bordetanext,
    required String deworlast,
    required String dewornext,
    required String deticklast,
    required String deticknext,
    required String anyotherlast,
    required String anyothernext,
    required String allergicMedicine,
    required String allergicFood,
    required String allergicgrass,
    required String medicationlast6,
    required String majorillness,
    required String fearOfThunder,
    required String fearDislike,
    required String bittenDog,
    required String bittenHuman,
    required String allergicMedicineC,
    required String allergicFoodC,
    required String allergicgrassC,
    required String medicationlast6C,
    required String majorillnessC,
    required String fearOfThunderC,
    required String fearDislikeC,
    required String bittenDogC,
    required String bittenHumanC,
    required BuildContext context,
    required Uint8List? sign,
  }) async {
    await auth.collection('pet details').doc(id).collection('pet').doc().set({
      "petname": petname,
      "breed": breed,
      "color": color,
      "dob": dob,
      "weight": weight,
      "lastheat": lastHeat,
      "nextheat": nextHeat,
      "gender": gender,
      "spayedNeutered": spayedNeutered,
      "vetName": vetName,
      "mobile": mobile,
      "petProneTo": petProneTo,
      "petPossessive": petPossessive,
      "parkDaycare": parkDaycare,
      "petAround": petAround,
      "petDescribe": petDescribe,
      "petExercise": petExercise,
      "mrngTime": mrngtime,
      "afrnTime": afrntime,
      "eveTime": evetime,
      "nytTime": nyttime,
      "mrngDiet": mrngdiet,
      "afrnDiet": afrndiet,
      "eveDiet": evediet,
      "nytDiet": nytdiet,
      "mrngqyt": mrngqyt,
      "afrnqyt": afrnqyt,
      "eveqyt": eveqyt,
      "nytqyt": nytqyt,
      "place": place,
      "date": date,
      //
      "isMedicaion": isMedicaion,
      "medication1": medication1,
      "dosage1": dosage1,
      "prescribe1": prescribe1,
      "medication2": medication2,
      "dosage2": dosage2,
      "prescribe2": prescribe2,
      "medication3": medication3,
      "dosage3": dosage3,
      "prescribe3": prescribe3,
      "isVaccinationC": isVaccinationC,
      "rabieslast": rabieslast,
      "rabiesnext": rabiesnext,
      "sevenlast": sevenlast,
      "sevennext": sevennext,
      "bordetalast": bordetalast,
      "bordetanext": bordetanext,
      "deworlast": deworlast,
      "dewornext": dewornext,
      "deticklast": deticklast,
      "deticknext": deticknext,
      "anyotherlast": anyotherlast,
      "anyothernext": anyothernext,
      "allergicMedicine": allergicMedicine,
      "allergicFood": allergicFood,
      "allergicgrass": allergicgrass,
      "medicationlast6": medicationlast6,
      "majorillness": majorillness,
      "fearOfThunder": fearOfThunder,
      "fearDislike": fearDislike,
      "bittenDog": bittenDog,
      "bittenHuman": bittenHuman,
      "allergicMedicineC": allergicMedicineC,
      "allergicFoodC": allergicFoodC,
      "allergicgrassC": allergicgrassC,
      "medicationlast6C": medicationlast6C,
      "majorillnessC": majorillnessC,
      "fearOfThunderC": fearOfThunderC,
      "fearDislikeC": fearDislikeC,
      "bittenDogC": bittenDogC,
      "bittenHumanC": bittenHumanC,
      'sign': sign
    }).then((value) => CustomSnackbar.buildSnackbar(
        context: context, message: 'Submit success'));
  }
}

class UpdatePet {
  static var auth = FirebaseFirestore.instance;
  static Future<void> UpdatePetDetails({
    required String userid,
    required String petid,
    required String petname,
    required String breed,
    required String color,
    required String dob,
    required String weight,
    required String lastHeat,
    required String nextHeat,
    required String gender,
    required String spayedNeutered,
    required String vetName,
    required String mobile,
    required String petProneTo,
    required String petPossessive,
    required String parkDaycare,
    required String petAround,
    required String petDescribe,
    required String petExercise,
    required String mrngtime,
    required String afrntime,
    required String evetime,
    required String nyttime,
    required String mrngdiet,
    required String afrndiet,
    required String evediet,
    required String nytdiet,
    required String mrngqyt,
    required String afrnqyt,
    required String eveqyt,
    required String nytqyt,
    required String place,
    required String date,
    //
    required String isMedicaion,
    required String medication1,
    required String dosage1,
    required String prescribe1,
    required String medication2,
    required String dosage2,
    required String prescribe2,
    required String medication3,
    required String dosage3,
    required String prescribe3,
    required String isVaccinationC,
    required String rabieslast,
    required String rabiesnext,
    required String sevenlast,
    required String sevennext,
    required String bordetalast,
    required String bordetanext,
    required String deworlast,
    required String dewornext,
    required String deticklast,
    required String deticknext,
    required String anyotherlast,
    required String anyothernext,
    required String allergicMedicine,
    required String allergicFood,
    required String allergicgrass,
    required String medicationlast6,
    required String majorillness,
    required String fearOfThunder,
    required String fearDislike,
    required String bittenDog,
    required String bittenHuman,
    required String allergicMedicineC,
    required String allergicFoodC,
    required String allergicgrassC,
    required String medicationlast6C,
    required String majorillnessC,
    required String fearOfThunderC,
    required String fearDislikeC,
    required String bittenDogC,
    required String bittenHumanC,

    //
    required BuildContext context,
  }) async {
    await auth
        .collection('pet details')
        .doc(userid)
        .collection('pet')
        .doc(petid)
        .update({
      "petname": petname,
      "breed": breed,
      "color": color,
      "dob": dob,
      "weight": weight,
      "lastheat": lastHeat,
      "nextheat": nextHeat,
      "gender": gender,
      "spayedNeutered": spayedNeutered,
      "vetName": vetName,
      "mobile": mobile,
      "petProneTo": petProneTo,
      "petPossessive": petPossessive,
      "parkDaycare": parkDaycare,
      "petAround": petAround,
      "petDescribe": petDescribe,
      "petExercise": petExercise,
      "mrngTime": mrngtime,
      "afrnTime": afrntime,
      "eveTime": evetime,
      "nytTime": nyttime,
      "mrngDiet": mrngdiet,
      "afrnDiet": afrndiet,
      "eveDiet": evediet,
      "nytDiet": nytdiet,
      "mrngqyt": mrngqyt,
      "afrnqyt": afrnqyt,
      "eveqyt": eveqyt,
      "nytqyt": nytqyt,
      "place": place,
      "date": date,
      //
      "isMedicaion": isMedicaion,
      "medication1": medication1,
      "dosage1": dosage1,
      "prescribe1": prescribe1,
      "medication2": medication2,
      "dosage2": dosage2,
      "prescribe2": prescribe2,
      "medication3": medication3,
      "dosage3": dosage3,
      "prescribe3": prescribe3,
      "isVaccinationC": isVaccinationC,
      "rabieslast": rabieslast,
      "rabiesnext": rabiesnext,
      "sevenlast": sevenlast,
      "sevennext": sevennext,
      "bordetalast": bordetalast,
      "bordetanext": bordetanext,
      "deworlast": deworlast,
      "dewornext": dewornext,
      "deticklast": deticklast,
      "deticknext": deticknext,
      "anyotherlast": anyotherlast,
      "anyothernext": anyothernext,
      "allergicMedicine": allergicMedicine,
      "allergicFood": allergicFood,
      "allergicgrass": allergicgrass,
      "medicationlast6": medicationlast6,
      "majorillness": majorillness,
      "fearOfThunder": fearOfThunder,
      "fearDislike": fearDislike,
      "bittenDog": bittenDog,
      "bittenHuman": bittenHuman,
      "allergicMedicineC": allergicMedicineC,
      "allergicFoodC": allergicFoodC,
      "allergicgrassC": allergicgrassC,
      "medicationlast6C": medicationlast6C,
      "majorillnessC": majorillnessC,
      "fearOfThunderC": fearOfThunderC,
      "fearDislikeC": fearDislikeC,
      "bittenDogC": bittenDogC,
      "bittenHumanC": bittenHumanC,
    }).then((value) => CustomSnackbar.buildSnackbar(
            context: context, message: 'Updated success'));
  }
}
